### ISSUE TITLE
Cosmos Upgrades .ical incorrect syntax

### ISSUE THREAD

**Issue by zanglang** [TedcryptoOrg/cosmos-tools#209]
https://icalendar.org/validator.html pointed out that this line towards the bottom of the ical is invalid and probably can be omitted:
```
BEGIN:VTIMEZONE
TZID:UTC
BEGIN:STANDARD
DTSTART:00000101T120000 <--- this line
TZNAME:UTC
TZOFFSETTO:+0000
```
Error reported:

    Invalid DTSTART value, must be a valid date or date-time value [near line # 74](javascript:void(0);)
    Reference: [3.3.5. Date-Time](http://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html)

**Comment by joshlopes** [comment]
Thanks. This has been fixed.
